* Введение.

  Scheme - это язык программирования общего назначения. Он является высокоуровневым, поддерживает операции над сложными
  типами данных, такими как строки, списки и векторы, а так же операции над традиционными типами
  данных, такими как числа и символы. Хотя Scheme часто ассоциируется с символьными (symbolic) приложениями, он так же
  имеет богатый набор типов данных и гибких управляющих структур, что делает его поистине гибким, разносторонним
  языком. Scheme использовался для написания текстовых редакторов, оптимизирующих компиляторов, операционных систем,
  графических пакетов, экспертных систем, числовых приложений, пакетов для финансового анализа, систем виртуальной
  реальности и практически в любой другой области, которую вы только сможете придумать. Scheme довольно простой язык для
  изучения, потому что он основан на небольшом количестве синтаксических форм и симантических идей, а интерактивная
  природа большинства реализаций способствует экспериментам с языком. В то же время довольно сложно изучить Scheme
  полностью - обретение способности использовать весь потенциал языка требует тщательного изучения и практики.

  Программы, написанные на Scheme, обладают высокой переносимостью между различными машинами (в рамках одной реализации
  Scheme), потому что все машинозависимые части обычно полностью сокрыты от программиста. Часто программы переносимы и
  между различными реализациями Scheme благодаря усилиям группы создателей языка, которые опубликовали серию отчётов
  "Revised Reports" для Scheme. Последний, "Revised6 Report" [fn:24], акцентирует внимание на переносимости, вводя ряд
  стандартных библиотек и стандартный механизм для определения новых переносимых библиотек и программ верхнего уровня.

  Несмотря на то, что ранние реализации Scheme были неэффективны и медлительны, многие новые, основанные на компиляции,
  реализации быстры и способны производить код, работающий на ровне с программами, написанными на низкоуровневых
  языках. Относительная неэффективность, которую часто вменяют языку, ввиду того, что он требует проведения некоторых
  проверок во время выполнения для поддержки обобщенной арифметики и возможности предоставления программисту достаточной
  информации для обнаружения и исправления ошибки - всё это может быть отключено в большинстве реализаций языка.

  Scheme поддерживает множество типов данных, или объектов, включая буквы, строки, символы, списки или векторы объектов,
  и полный набор числовых типов данных, таких как комплексные, дробные, с плавающей точкой, рациональные числа.

  Память, требуемая под хранение содержимого объектов, выделяется динамически по необходимости и сохраняется до тех пор,
  пока используется, а затем автоматически освобождается, обычно, сборщиком мусора, который периодически очищает память
  от неиспользуемых объектов. Простые атомарные значения, такие как маленькие числа, буквы, булевы значения и пустые
  списки, обычно представлены в виде непосредственно своих значений и не требуют дополнительных затрат на выделения и
  освобождения памяти.

  Независимо от представления, /все/ данные являются объектами первого класса. Все они хранятся независимо и могут
  свободно передаваться как аргументы в процедуры, возвращаться как значение из процедуры, или комбинироваться для
  образования новых объектов.

  Это выделяет Scheme из множества других языков, где под составные структуры данных, такие как массивы, память
  выделяется статически и никогда не освобождается, выделяется при входе в блок кода и освобождается независимо от
  остальных условий при выходе из блока, или же выделяется и освобождается  программистом явно.

  Scheme относится к языкам с /вызовом-по-значению/ , но для, по меньшей мере,  мутабельных объектов (объекты, которые
  могут быть изменены), значением является указатель на реальное место хранения объекта. Эти указатели остаются за
  сценой, так что программисту нет нужды вдаваться в подробности их работы, за исключением лишь того, что бы понимать,
  что реальное значение содержимого хранилища объекта не копируется, когда объект передаётся или возвращается из
  процедуры.

  В сердце языка Scheme лежит небольшой набор синтаксических форм, из которых построены все остальные формы. Эти
  ключевые формы, расширенный набор синтаксических форм, выведенных из оных, вместе с примитивными процедурами и
  составляют язык Scheme. Интерпретатор или компилятор для Scheme может быть крайне мал, потенциально быстр и
  надёжен. Расширенные синтаксические формы и многие основные процедуры могут быть написаны на самом же Scheme, упрощая
  реализацию и увеличивая надёжность.

  Программы и структуры данных на Scheme выглядят одинаково, имеют одинаковое печатное представление. Как результат,
  любая программа на Scheme естественным и понятным образом представляется в виде объекта данных Scheme. Например,
  переменные и синтаксические ключевые слова представлены символами, в то время как структурированные синтаксические
  формы представлены в виде списков. Это представление лежит в основе возможностей по расширению синтаксиса,
  предоставляемых Scheme, для определения новых синтаксических форм в терминах уже существующих синтаксических форм и
  процедур. Это так же значительно облегчает написание интерпретаторов, компиляторов и других преобразующих код
  Scheme инструментов, непосредственно на самом же Scheme, а так же программ, преобразующих код других языков в Scheme.

  В Scheme ключевые слова и переменные имеют лексическую область видимости, а программы имеют блочную структуру.
  Идентификаторы могут быть импортированы в программу или библиотеку, или связаны локально в пределах блока
  кода, такого как библиотека, программа или тело процедуры. Локальное связывание имеет лексическую область видимости
  т.е. только в тексте программы, который составляет конкретный блок кода. Упоминание идентификатора с тем же именем за
  пределами этого блока кода, будет указывать на другой объект. Блоки могут быть вложенными, и связывания во внутреннем
  блоке могут /затенять/ связывания с тем же идентификатором в окружающем его блоке. Область связывания - это блок, в
  котором идентификатор связан, минус любые участки блока, в которых идентификатор затенён. Блочная структура и
  лексическая область видимости позволяют создавать программы, которые будут модульными, легко читаемыми,
  поддерживаемыми и надёжными. Лексическая область видимости так же позволяет производить эффективный код, потому что
  компилятор способен определить области действия всех связываний еще до выполнения программы и провести связывание
  с тем, во что раскрылась бы каждая ссылка на идентификатор в итоге. Это конечно не значит, что компилятор способен
  определить значения всех переменных, поскольку фактические значения не вычисляются в большинстве случаев до тех пор,
  пока программа не выполнится.

  В большинстве языков, объявление процедуры это просто сопоставление имени с блоком кода. Определённые переменные,
  локальные для этого блока, являются параметрами процедуры. В некоторых языках, процедура может быть объявлена пределах
  другого блока или процедуры, и существовать до тех пор, пока выполнение этого участка кода не достигнет конца блока.
  В других, процедуры могут быть объявлены только на верхнем уровне. В Scheme, объявление процедуры может быть
  произведено внутри другого блока или процедуры и эта процедура затем может быть выполнена в любое время, даже когда
  внешний блок кода завершил своё выполнение. Для поддержки лексической области видимости, процедура, помимо самого
  кодом, хранит в себе лексический контекст (окружение).

  Более того, процедуры в Scheme не всегда имеют имена. Вместо этого, процедуры являются объектами первого класса,
  такими как строки или числа, и переменная может быть связана с процедурой тем же способом, как связывается с любым
  другим объектом.

  Процедуры в Scheme, так же как и в большинстве других языков, могут быть рекурсивными. Это значит, что любая
  процедура, прямо или косвенно, может вызывать саму себя. Многие алгоритмы, будучи представленными в рекурсивном виде,
  становятся элегантнее или эффективнее. Особый вид рекурсии, называемый /хвостовая рекурсия/, используется для
  выражения итераций или циклов. Вызов считается хвостовым, когда одна процедура прямо возвращает результат выполнения
  другой процедуры. Рекурсия считается хвостовой, когда процедура, прямо или косвенно, рекурсивно делает хвостовой вызов
  самой себя. Ко всем реализациям Scheme предъявляется требование, реализовать хвостовые вызовы в виде переходов
  (gotos), а значит, накладные расходы по памяти и стеку, обычно ассоциируемые с рекурсией, устраняются. Как результат,
  Scheme программистам нужно лишь разобраться в обычных вызовах процедур и рекурсии, и нет никакой нужды обременять себя
  обычным набором итерационных конструкций.

  Scheme поддерживает определение произвольных управляющих структур с помощью /продолжений/ . /Продолжение/ , это
  процедура, которая заключает в себе остальную часть программы в заданной точке. /Продолжение/ может быть получено в
  любой момент во время выполнения программы. Так же, как и с другими процедурами, /продолжение/ является объектом
  первого класса и может быть выполнено в любой момент после его создания. Когда оно выполняется, программа немедленно
  продолжает выполнение с той точки, где это /продолжение/ было создано. /Продолжения/ позволяют реализовать сложные
  механизмы управления, включая поиск с возвратом, многопоточность и сопрограммы.

  Scheme так же позволяет программистам создавать новые синтаксические формы, или синтаксические выражения, путём
  написания преобразующих процедур, определяющих, как каждая новая синтаксическая форма будет преобразовываться в
  существующие синтаксические формы. Эта преобразующая процедура сама по себе выражается в Scheme с помощью удобного
  высокоуровневого языка шаблонов, который берёт на себя заботы по проверке синтаксиса, деконструкции входных данных и
  реконструкции выходных. По умолчанию, лексическая область видимости действует так же и для подобных преобразующих
  процессов, однако программист может осуществлять контроль над областью действия всех идентификаторов, появляющихся на
  выходе преобразователя. Синтаксические выражения полезны для объявления новых языковых конструкций, для имитации
  языковых конструкций, найденных в других языках программирования, для достижения эффекта встраивания (in-line)
  выражений, а так же для имитации целого языка. Большинство больших программ на Scheme представляют из себя комбинацию
  синтаксических выражений и объявлений процедур.

  Scheme произошел от Lisp'a и считается его диалектом. Scheme унаследовал от Lisp'a подход к работе с значениями, как
  объектами первого класса, ряд важных структур данных, включая символы и списки, представление программ как объектов, и
  многое другое. Лексическая область видимости и блочная структура - возможности, позаимствованные из Algol
  60 [fn:21]. Scheme был первым диалектом Lisp'a, впитавшим в себя идеи лексической области видимости и блочной
  структуры, процедур первого класса, оптимизацию хвостовой рекурсии, продолжения, и синтаксических выражений с
  лексической областью действия.

  Common Lisp [fn:27] и Scheme являются современными потомками Lisp'a, и развитие каждого из них так же сказывается и на
  другом. Как и в Scheme, но чего не было в ранних версиях Lisp'а, Common Lisp перенял лексическую область видимости и
  процедуры первого класса, не смотря на то, что в Common Lisp средства построения синтаксических выражений не считаются
  с лексической областью видимости. В Common Lisp правила обработки процедур отличаются от правил обработки остальных
  объектов, так же он поддерживает отдельное пространство имён для процедур, что препятствует использованию процедур как
  объектов первого класса. И хотя Common Lisp не поддерживает /продолжения/ или требует правильного обращения с
  хвостовыми вызовами, однако он поддерживает ряд менее общих структур данных, которых нет в Scheme. Хотя оба языка
  похожи, Common Lisp включает в себя более специализированные конструкции, в то время как Scheme включает в себя более
  универсальные строительные блоки, из которых могут быть построены такие конструкции (и другие).

  Остаток этой главы содержит в себе описание синтаксиса Scheme, соглашений в именовании и типографических соглашений,
  используемых в этой книге.

** Синтаксис

   Программы на Scheme состоят из ключевых слов, переменных, структурирующих форм, константных данных (числа, буквы,
   строки, цитируемые векторы, цитируемые списки, цитируемые символы и т.д.), пробелов и комментариев.

   Ключевые слова, переменные и символы собирательно именуются идентификаторами. Идентификаторы могут быть образованы из
   букв, чисел и некоторых специальных символов, включающих ~?~, ~!~, ~.~, ~+~, ~-~, ~*~, ~/~, ~<~, ~=~, ~>~, ~:~, ~$~,
   ~%~, ~^~, ~&~, ~_~, ~~~, и ~@~, так же ряда дополнительных символов из Unicode. Идентификаторы не могут начинаться со
   знака @, а так же со знаков, с которых может начинаться число, таких как ~+~, ~-~, ~.~, исключение ~-~ знаки ~+~, ~-~
   и некоторые другие, которые могут быть идентификаторами сами по себе, а так же идентификаторы, начинающиеся с
   ~->~. Например, ~hi~, ~Hello~, ~n~, ~x~, ~x3~, ~x+2~, и ~?$&*!!!~ - корректные идентификаторы. Идентификаторы
   отделяются пробелами, комментарием, скобками, фигурными скобками, двойными кавычками и знаком решётки. Разделитель,
   или любая другая буква Unicode, могут быть включены в любое место в имени идентификатора путём экранирования в виде
   ~\xsv~, где sv - скалярное значение символа в шестнадцатеричном представлении.

   На длину идентификаторов не накладывается никаких ограничений, программист использовать столько символов в имени,
   сколько посчитает нужным. Однако, длинные идентификаторы не заменят комментариев, в то же время, их частое
   использование может сделать код трудным для форматирования и чтения. Хорошее правило, это использовать короткие имена
   идентификаторов в тех случаях, когда область видимости идентификатора мала, и длинные тогда, когда область видимости
   велика.

   Идентификаторы могут содержать любую комбинацию символов верхнего или нижнего регистров, регистр учитывается т.е. два
   идентификатора считаются различными, даже если они отличаются только регистром. Например, ~abcde~, ~Abcde~, ~AbCdE~ и
   ~ABCDE~ - все различные идентификаторы. Это нововведение, по сравнению с предыдущими отчётами по стандарту языка.

   Структурированные формы и списки констант заключаются в скобки, например ~(a b c)~ или ~(* (- x 2) y)~. Пустой список
   записывается как ~()~. Другие парные наборы скобок, такие как ~[~ ~]~, могут быть использованы вместо круглых скобок
   и часто используются для выделения подвыражений определенных стандартных синтаксических форм для удобочитаемости, как
   в примерах в этой книге. Векторы записываются таким же образом, как и списки, за исключением того, что они начинаются
   с ~#(~ и заканчиваются ~)~, например ~#(это вектор содержащий символы)~. Байт-векторы записываются как
   последовательность беззнаковых байтов (обычные целочисленные значения в диапазоне от 0 до 255), заключенных в ~#vu8(~
   и ~)~, например ~#vu8(3 250 45 73)~.

   Строки заключаются в двойные кавычки, например "Это строка" . Буквы предваряются ~#\~, например ~#\a~. Когда речь
   идёт о строках или буквах - регистр имеет значение, так же как и в случае с идентификаторами. Числа могут быть
   записаны в виде целочисленного значения (integer), например ~-123~, рационального числа, например ~1/2~, числа с
   плавающей точкой или в научной форме, например ~1.3~ или ~1e23~, как комплексное число, в прямоугольной или полярной
   системах координат например ~1.3-2.7i~ или ~-1.2@73~. В случае чисел регистр не имеет значения. Булевы значения,
   представляющие ложь и истину, обозначаются ~#f~ и ~#t~ соответственно. В Scheme, условные выражения обычно считают
   ~#f~ ложью, а любой другой объект истиной, так что ~3~, ~0~, ~()~, "false" или ~nil~ - всё это считается истиной.

   Детальное описание синтаксиса каждого константного типа данных дано в отдельной секции в главе 6 и в формальном
   описании синтаксиса, приведённом в конце книги.

   Выражения в Scheme могут занимать несколько строк, для этого не требуются специальные терминирующие
   символы. Учитывая, что количество пробельных символов и переводов строки между выражениями не имеет синтаксического
   значения, эту возможность следует использовать, чтобы программы на Scheme были выровнены таким образом, чтобы
   правильно отображать структуру кода и делать его настолько читаемым, насколько это возможно. Комментарии могут быть
   размещены в каждой строке программы, между символом ~;~ и концом строки. Комментарий, поясняющий конкретное выражение
   Scheme, обычно размещается в предыдущей строке, с тем же уровнем отступа. Комментарии, поясняющие процедуру или
   группу процедур, обычно размещаются перед процедурой, без отступа.

   Так же поддерживаются следующие два вида комментариев: блочные и комментарии по данным (datum). Блочные комментарии
   обосабливаются парой ~#|~ и ~|~, и могут быть вложенными. Комментарии данных начинаются с префикса ~#;~ , за которым
   следует печатная версия объекта данных. Комментарии по данным обычно используются, чтобы закомментировать конкретное
   объявление или выражение. Например, ~(список из трёх #;(а не четырёх) элементов)~. Комментарии по данным могут так же
   быть вложенными, например ~#;#;(a)(b)~, но это не имеет какого то особого значения, в сравнении, если бы
   комментировался каждый элемент по отдельности.

   Некоторые значения в Scheme, такие как процедуры или порты, не имеют стандартизированного печатного представления и
   по этому не могут быть представлены константой при печати. В этой книге используется обозначение ~#<пояснение>~,
   когда мы хотим оказать возвращаемый результат какой либо операции, возвращающей одно из таких значений, например
   ~#<procedure>~ или ~#<port>~.

** Соглашения в именовании

   Соглашения по именованию, принятые в Scheme, разработаны так, чтобы обеспечивать высокий уровень системности и
   регулярности. Ниже приведён список таких соглашений:

   + Имена предикатов заканчиваются символом вопроса (?). Предикаты, это процедуры, возвращающие истину или ложь, такие
     как ~eq?~, ~zero?~ и ~string=?~. Обычные для чисел операции сравнения, такие как ~=~, ~<~, ~>~, ~<=~, и ~>=~
     являются исключением из правил.
   + Предикаты типов, например ~pair?~, составляются из имени типа, в данном случае /pair/ и знака вопроса.
   + Имена большинства процедур предикатов для букв, строк и векторов начинаются с префикса ~char-~, ~string-~,
     ~vector-~, например ~string-append~. (Имена некоторых процедур для списков начинаются с ~list-~, но большинство
     нет)
   + Имена процедур, которые преобразуют объект одного типа в объект другого типа, записываются как ~type1->type2~,
     например ~vector->list~.
   + Имена процедур и синтаксических форм, производящих побочные эффекты, оканчиваются знаком восклицательного знака
     (~!~). Например ~set!~ и ~vector-set!~. Процедуры, производящие операции ввода-вывода, формально так же считаются
     процедурами с побочными эффектами, однако они попадают под исключение из правил.
   + Программистам следует следовать этим соглашениям по именованию там, где это возможно.

** Типографические и нотационные соглашения
   Про стандартные процедуры или синтаксические формы, единственная цель которых выполнение побочных эффектов, сказано,
   что возвращаемый ими результат не определён. Это значит, что конкретная реализация свободна возвращать любое
   количество значений, каждое из которых может быть любым объектом Scheme. Не рассчитывайте на то, что эти возвращаемые
   значения одинаковы для всех реализаций, одинаковые для версий одной и той же реализации, или даже одинаковы между
   двумя вызовами одной и той же процедуры или синтаксической формы. Некоторые реализации Scheme используют специальные
   объекты для обозначения неопределённого значения. Печать этого объекта часто подавляется интерактивными системами
   Scheme, поэтому значения выражений, возвращающих неопределённые значения, не печатаются.

   В то время, как большинство стандартных процедур возвращает одно значение, язык поддерживает процедуры, которые
   возвращают ноль, одно, более одного, или переменное количество значений, используя механизм, описанный в главе
   5.8. Некоторые стандартные выражения могут вычисляться в множество значений, если одно из подвыражений вычисляется в
   множество значений т.е. когда вызывается процедура, возвращающая несколько значений. Когда такое случается, выражению
   предписано возвращать /значения/, а не /значение/ его подвыражения. То же касается стандартных процедур, принимающих
   аргументом функцию - им предписывается возвращать множественное значение в том случае, если процедура-аргумент,
   влияющая на результат, возвращает множественное значение.

   В этой книге используются слова 'должен' и 'следует', чтобы описать программные требования, такие как требование,
   чтобы передаваемый индекс был меньше, чем длина вектора, при вызове ~vector-ref~. Если использовано слово 'должен', это
   значит, что реализация будет отслеживать выполнение этих требований т.е. будет выброшено исключение, обычно с типом
   условия ~&assertion~. Если используется слово 'следует', исключение может быть выброшено, а может не быть, если нет -
   поведение программы не определено. Фраза 'нарушение синтаксиса' используется, чтобы описать ситуацию, когда программа
   сформирована неправильно. Нарушения синтаксиса обнаруживаются в основном при выполнении программы. Когда нарушение
   синтаксиса обнаружено, выбрасывается исключение типа ~&syntax~ и программа прекращает работу.

   Типографические соглашения, используемые в этой книге весьма просты. Все объекты напечатаны таким же образом, как они
   выглядели бы, если бы их набрали на клавиатуре. Это касается ключевых слов синтаксиса, переменных, константных
   объектов, выражений Scheme, и примеров программ. Выделение /курсивом/ используется для обозначения синтаксических
   переменных в пояснениях синтаксических форм, аргументов и процедур. Так же курсивом выделены технических термины,
   используемые впервые. Обычно, имена и синтаксические формы находятся в нижнем регистре, даже если они начинают новое
   предложение.  То же касается и синтаксических переменных, выделенных курсивом.

   В описании синтаксических форм и процедур, один или несколько прототипов шаблонов показывают синтаксическую форму или
   формы или корректное количество аргументов для применения процедуры. Ключевое слово или имя процедуры выделяются
   машинописным шрифтом, так же как и круглые скобки. Остальные части синтаксиса или аргументы выделяются курсивом,
   используя имя, обозначающее тип выражения или аргумента, ожидаемого синтаксической формой или процедурой. Окружности
   используются для обозначения нуля или более вхождений подвыражения или аргумента. Например, ~(or expr ...)~
   описывает синтаксическую форму ~or~, которая имеет ноль или более подвыражений, и ~(member obj list)~ описывает
   процедуру ~member~, которая ожидает два аргумента - объект и список.

   In the description of a syntactic form or procedure, one or more prototype patterns show the syntactic form or forms
   or the correct number or numbers of arguments for an application of the procedure. The keyword or procedure name is
   given in typewriter font, as are parentheses. The remaining pieces of the syntax or arguments are shown in italics,
   using a name that implies the type of expression or argument expected by the syntactic form or procedure. Ellipses
   are used to specify zero or more occurrences of a subexpression or argument. For example, (or expr ...) describes the
   or syntactic form, which has zero or more subexpressions, and (member obj list) describes the member procedure, which
   expects two arguments, an object and a list.

   A syntax violation occurs if the structure of a syntactic form does not match its prototype. Similarly, an exception
   with condition type &assertion is raised if the number of arguments passed to a standard procedure does not match
   what it is specified to receive. An exception with condition type &assertion is also raised if a standard procedure
   receives an argument whose type is not the type implied by its name or does not meet other criteria given in the
   description of the procedure. For example, the prototype for vector-set! is

   (vector-set! vector n obj)

   and the description says that n must be an exact nonnegative integer strictly less than the length of vector. Thus,
   vector-set! must receive three arguments, the first of which must be a vector, the second of which must be an exact
   nonnegative integer less than the length of the vector, and the third of which may be any Scheme value. Otherwise, an
   exception with condition type &assertion is raised.

   In most cases, the type of argument required is obvious, as with vector, obj, or binary-input-port. In others, primarily
   within the descriptions of numeric routines, abbreviations are used, such as int for integer, exint for exact integer,
   and fx for fixnum. These abbreviations are explained at the start of the sections containing the affected entries.
